/**
 * A4.00 — DDOT Standard Details sheet.
 *
 * The Queen's English A2.01 pattern: DDOT's OWN standard details,
 * embedded near-verbatim and toggled by site condition, instead of
 * redrawn. What embeds here:
 *
 *   - The §4.2 barrier-placement plan diagram MATCHING this site's
 *     barrier type (Type 1 vs Type 2 — only the applicable one prints).
 *   - The three Appendix 3 reflector drawings (DWG 610.06/07/08,
 *     chief-engineer signed — embedding preserves the signature).
 *   - The Appendix 6 precast concrete curb barrier detail, stamped
 *     "NOT REQUIRED" when a bike lane is present — DDOT approved
 *     exactly that stamp on the Queen's English set.
 *   - Appendix 5 typeset fresh (it's tabular data, not a drawing):
 *     utility operator contacts + the APWA color code.
 *
 * Figures come from src/design/assets/guidelineFigures.ts (generated by
 * scripts/extract-guideline-assets.sh); each prints its provenance
 * caption so a reviewer can trace every embedded drawing to its source.
 */

import {
  concreteBlockDetail,
  reflectorSpecs,
  reflectorsSideMounted,
  reflectorsTopMounted,
  type GuidelineFigure,
  type1PlanDiagram,
  type2PlanDiagram,
} from "../assets/guidelineFigures.js";
import { sheetTitleForView } from "../sheetIndex.js";
import type { SiteContext } from "../siteContext.js";
import type { StreateryDesign } from "../types.js";
import { escapeXml } from "./shared.js";
import { composeSheet, wrapText } from "./sheetChrome.js";

// ---------- Sheet layout constants (drawing units = feet) ----------

const COL_X = [2, 58] as const;
const FIG_W = 52;
const CAPTION_FONT = 0.75;
const FIG_GAP = 2.6;

/** APWA Uniform Color Code, per Appendix 5 of the guidelines. */
const APWA_ROWS: Array<{ color: string; label: string; desc: string }> = [
  { color: "#ffffff", label: "WHITE", desc: "Proposed Excavation" },
  { color: "#ff8ad8", label: "PINK", desc: "Temporary Survey Markings" },
  { color: "#e8112d", label: "RED", desc: "Electric Power Lines, Cables, Conduit, Lighting Cables" },
  { color: "#ffd700", label: "YELLOW", desc: "Gas, Oil, Steam, Petroleum, or Gaseous Materials" },
  { color: "#ff7f27", label: "ORANGE", desc: "Communication, Alarm or Signal Lines, Cables or Conduit" },
  { color: "#0066ff", label: "BLUE", desc: "Potable Water" },
  { color: "#7f3fbf", label: "PURPLE", desc: "Reclaimed Water, Irrigation, and Slurry Lines" },
  { color: "#00b140", label: "GREEN", desc: "Sewers and Drain Lines" },
];

/** Appendix 5 utility operator contacts, verbatim. */
const UTILITY_OPERATORS: Array<[string, string]> = [
  ["DC Water", "202-612-3400"],
  ["PEPCO", "877-737-2662"],
  ["Verizon", "804-644-3108"],
  ["Washington Gas", "844-927-4427"],
];

export function buildDdotDetailsSvg(
  design: StreateryDesign,
  site: SiteContext,
): string {
  const el: string[] = [];

  el.push(
    `<text x="${COL_X[0]}" y="0" font-size="1.6" font-family="sans-serif" font-weight="700" fill="#1c1917">DDOT STANDARD DETAILS</text>`,
    `<text x="${COL_X[0]}" y="1.7" font-size="0.9" font-family="sans-serif" fill="#78716c">DDOT's own standard drawings, embedded near-verbatim per the approved Queen's English precedent — not redrawn. Provenance under each figure.</text>`,
  );

  /**
   * Place a figure at (x, y), return the y just past its caption.
   * Width is fixed; height follows the crop's aspect ratio so DDOT's
   * drawings are never distorted. `overlay` (if given) is called with
   * the figure's center so stamps can position themselves.
   */
  const placeFigure = (
    fig: GuidelineFigure,
    x: number,
    y: number,
    overlay?: (centerX: number, centerY: number) => string[],
  ): number => {
    const h = (FIG_W * fig.heightPx) / fig.widthPx;
    el.push(
      `<image x="${x}" y="${y}" width="${FIG_W}" height="${h}" href="${fig.dataUri}" />`,
      `<rect x="${x}" y="${y}" width="${FIG_W}" height="${h}" fill="none" stroke="#a8a29e" stroke-width="0.06" />`,
    );
    if (overlay) el.push(...overlay(x + FIG_W / 2, y + h / 2));
    let capY = y + h + 1.0;
    for (const line of wrapText(fig.caption, Math.floor(FIG_W / (CAPTION_FONT * 0.45)))) {
      el.push(
        `<text x="${x}" y="${capY}" font-size="${CAPTION_FONT}" font-family="sans-serif" font-style="italic" fill="#57534e">${escapeXml(line)}</text>`,
      );
      capY += 1.0;
    }
    return capY + FIG_GAP;
  };

  // ---------- Column A: barrier placement + side-mounted + specs ----------
  // Only the diagram for THIS street's barrier type prints — embedding
  // both would invite building the wrong one.

  let yA = 4;
  const planFig =
    design.barrierType === "type1" ? type1PlanDiagram : type2PlanDiagram;
  yA = placeFigure(planFig, COL_X[0], yA);
  yA = placeFigure(reflectorsSideMounted, COL_X[0], yA);
  yA = placeFigure(reflectorSpecs, COL_X[0], yA);

  // ---------- Column B: top-mounted + concrete block (+ stamp) + Appendix 5 ----------

  let yB = 4;
  yB = placeFigure(reflectorsTopMounted, COL_X[1], yB);

  // The QE-precedent toggle: bike lane present → DDOT accepted the
  // concrete-block detail stamped NOT REQUIRED. The figure still prints
  // (the reviewer sees what was waived); the stamp carries the decision.
  const notRequiredStamp = (cx: number, cy: number): string[] => [
    `<g transform="translate(${cx}, ${cy}) rotate(-18)">`,
    `<rect x="${-(FIG_W - 8) / 2}" y="-3.1" width="${FIG_W - 8}" height="6.2" fill="#fff" fill-opacity="0.85" stroke="#b91c1c" stroke-width="0.22" />`,
    `<text x="0" y="-1.2" font-size="1.45" font-family="sans-serif" font-weight="700" text-anchor="middle" fill="#b91c1c">NOT REQUIRED DUE TO</text>`,
    `<text x="0" y="0.6" font-size="1.45" font-family="sans-serif" font-weight="700" text-anchor="middle" fill="#b91c1c">PRESENCE OF BIKE LANES</text>`,
    `<text x="0" y="2.2" font-size="0.7" font-family="sans-serif" text-anchor="middle" fill="#b91c1c">§4.2 — QUEEN'S ENGLISH PRECEDENT; CONFIRM WITH DDOT</text>`,
    `</g>`,
  ];
  yB = placeFigure(
    concreteBlockDetail,
    COL_X[1],
    yB,
    site.rightOfWay.hasBikeLane ? notRequiredStamp : undefined,
  );

  // Appendix 5, typeset: operators table + APWA swatches.
  el.push(
    `<text x="${COL_X[1]}" y="${yB}" font-size="1.1" font-family="sans-serif" font-weight="700" fill="#1c1917">UTILITY OPERATOR CONTACTS (APPENDIX 5)</text>`,
  );
  yB += 1.6;
  for (const [operator, phone] of UTILITY_OPERATORS) {
    el.push(
      `<text x="${COL_X[1]}" y="${yB}" font-size="0.95" font-family="sans-serif" fill="#44403c">${escapeXml(operator)}</text>`,
      `<text x="${COL_X[1] + 18}" y="${yB}" font-size="0.95" font-family="sans-serif" fill="#44403c">${escapeXml(phone)}</text>`,
    );
    yB += 1.35;
  }
  yB += 1.2;
  el.push(
    `<text x="${COL_X[1]}" y="${yB}" font-size="1.1" font-family="sans-serif" font-weight="700" fill="#1c1917">APWA UNIFORM COLOR CODE (APPENDIX 5)</text>`,
  );
  yB += 1.6;
  for (const row of APWA_ROWS) {
    el.push(
      `<rect x="${COL_X[1]}" y="${yB - 1.0}" width="3" height="1.2" fill="${row.color}" stroke="#1c1917" stroke-width="0.05" />`,
      `<text x="${COL_X[1] + 3.8}" y="${yB}" font-size="0.85" font-family="sans-serif" font-weight="700" fill="#1c1917">${row.label}</text>`,
      `<text x="${COL_X[1] + 10}" y="${yB}" font-size="0.85" font-family="sans-serif" fill="#44403c">${escapeXml(row.desc)}</text>`,
    );
    yB += 1.5;
  }

  const bottomY = Math.max(yA, yB);
  const sheetMaxX = COL_X[1] + FIG_W + 2;

  return composeSheet(
    {
      viewTitle: sheetTitleForView("ddot-details"),
      design,
      sheetMinX: 0,
      sheetMaxX,
      sheetMinY: -7,
      contentBottomY: bottomY + 1,
      watermarkCenter: { x: sheetMaxX / 2, y: bottomY / 2 },
      hideNotesBand: true,
    },
    el,
  );
}
